propertiesserver.port=8080
spring.application.name=agenda

app.datasource.url=${url}
app.datasource.username=${username}
app.datasource.password=${password}
app.datasource.driver-class-name=com.mysql.cj.jdbc.Driver