server.port=8080
spring.application.name=agenda
spring.config.import=optional:file:.env[.properties]
# Database Configuration
spring.datasource.url=${URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
